name: Run Automate Preprocessing
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  preprocessing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.11'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn
      - name: Run Automate Preprocessing
        run: python preprocessing/automate_JohanadiSantoso.py
      - name: Commit Preprocessed Dataset
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add preprocessing/personality_dataset_preprocessing.csv
          git commit -m "Add preprocessed dataset via GitHub Actions" || echo "No changes to commit"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/johanadis/Eksperimen_SML_JohanadiSantoso.git
      - name: Upload Preprocessed Dataset
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-dataset
          path: preprocessing/personality_dataset_preprocessing.csv
