name: Preprocessing Dataset Otomatis

on:
  push:
    paths:
      - "preprocessing/automate_JohanadiSantoso.py"
      - "personality_dataset.csv"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    - name: Create preprocessing directory
      run: mkdir -p preprocessing

    - name: Jalankan script preprocessing
      run: python preprocessing/automate_JohanadiSantoso.py

    - name: Cek hasil preprocessing
      run: |
        echo "Daftar isi direktori:"
        ls -R
        echo "Isi file hasil preprocessing:"
        cat preprocessing/personality_dataset_preprocessing.csv

    - name: Upload Hasil Preprocessing
      uses: actions/upload-artifact@v4
      with:
        name: processed-dataset
        path: preprocessing/personality_dataset_preprocessing.csv
  
    - name: Commit dan Push file hasil preprocessing ke repo
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add preprocessing/personality_dataset_preprocessing.csv
        git commit -m "Update hasil preprocessing otomatis"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
