name: Train Models
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  train:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Membangun_model/requirements.txt || true
      - name: Run training with tuning
        run: python Membangun_model/modelling_tuning.py
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/johanadis/Eksperimen_SML_JohanadiSantoso.mlflow
          MLFLOW_TRACKING_USERNAME: johanadis
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      - name: Periksa Direktori Artefak
        run: |
          if [ -d "Membangun_model/artifacts" ] && [ "$(ls -A Membangun_model/artifacts)" ]; then
            echo "Direktori artifacts ada dan berisi file."
          else
            echo "Direktori artifacts tidak ada atau kosong."
            exit 1
          fi
      - name: Periksa Direktori Plot
        run: |
          if [ -d "Membangun_model/plots" ] && [ "$(ls -A Membangun_model/plots)" ]; then
            echo "Direktori plots ada dan berisi file."
          else
            echo "Direktori plots tidak ada atau kosong."
            exit 1
          fi
      - name: Unggah Artefak Model
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: Membangun_model/artifacts/
      - name: Unggah Plot
        uses: actions/upload-artifact@v4
        with:
          name: plots
          path: Membangun_model/plots/
      - name: Commit artifacts
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add Membangun_model/plots/*.png || true
          git add Membangun_model/plots/tuned/*.png || true
          git add Membangun_model/artifacts/ || true
          git commit -m "Add MLflow artifacts via GitHub Actions" || echo "No changes to commit"
          git push https://x:${{ secrets.GITHUB_TOKEN }}@github.com/johanadis/Eksperimen_SML_JohanadiSantoso.git
