name: Train Models
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  train:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Membangun_model/requirements.txt || true
      - name: Run training with tuning
        run: python Membangun_model/modelling_tuning.py
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/johanadis/Eksperimen_SML_JohanadiSantoso.mlflow
          MLFLOW_TRACKING_USERNAME: johanadis
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      - name: Buat Direktori Artifacts dan Plots
        run: |
          mkdir -p Membangun_model/artifacts
          mkdir -p Membangun_model/plots
          echo "Direktori Membangun_model/artifacts dan Membangun_model/plots telah dibuat atau sudah ada."
      - name: Debug Isi Direktori
        run: |
          echo "Isi direktori Membangun_model setelah pelatihan:"
          ls -R Membangun_model/
      - name: Periksa Isi Direktori Artefak
        run: |
          if [ "$(ls -A Membangun_model/artifacts)" ]; then
            echo "Direktori artifacts berisi file."
          else
            echo "Peringatan: Direktori artifacts kosong. Periksa modelling_tuning.py untuk memastikan file disimpan."
          fi
      - name: Periksa Isi Direktori Plot
        run: |
          if [ "$(ls -A Membangun_model/plots)" ]; then
            echo "Direktori plots berisi file."
          else
            echo "Peringatan: Direktori plots kosong. Periksa modelling_tuning.py untuk memastikan file disimpan."
          fi
      - name: Unggah Artefak Model
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: Membangun_model/artifacts/
      - name: Unggah Plot
        uses: actions/upload-artifact@v4
        with:
          name: plots
          path: Membangun_model/plots/
      - name: Commit artifacts
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add Membangun_model/plots/*.png || true
          git add Membangun_model/plots/tuned/*.png || true
          git add Membangun_model/artifacts/ || true
          git commit -m "Add MLflow artifacts via GitHub Actions" || echo "No changes to commit"
          git pull --rebase origin main
          git push https://x:${{ secrets.GITHUB_TOKEN }}@github.com/johanadis/Eksperimen_SML_JohanadiSantoso.git