name: Train Models
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  train:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Membangun_model/requirements.txt || true
      - name: Run training with tuning
        run: python Membangun_model/modelling_tuning.py
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/johanadis/Eksperimen_SML_JohanadiSantoso.mlflow
          MLFLOW_TRACKING_USERNAME: johanadis
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      - name: Buat Direktori Artifacts dan Plots
        run: |
          mkdir -p artifacts/tuned
          mkdir -p plots/tuned
          echo "Direktori artifacts/tuned dan plots/tuned telah dibuat atau sudah ada."
      - name: Debug Isi Direktori
        run: |
          echo "Isi direktori setelah pelatihan:"
          ls -R artifacts/
          ls -R plots/
      - name: Periksa Isi Direktori Artefak
        run: |
          if [ "$(ls -A artifacts/tuned)" ]; then
            echo "Direktori artifacts/tuned berisi file."
          else
            echo "Peringatan: Direktori artifacts/tuned kosong. Periksa modelling_tuning.py untuk memastikan file disimpan."
          fi
      - name: Periksa Isi Direktori Plot
        run: |
          if [ "$(ls -A plots/tuned)" ]; then
            echo "Direktori plots/tuned berisi file."
          else
            echo "Peringatan: Direktori plots/tuned kosong. Periksa modelling_tuning.py untuk memastikan file disimpan."
          fi
      - name: Unggah Artefak Model
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: artifacts/tuned/
      - name: Unggah Plot
        uses: actions/upload-artifact@v4
        with:
          name: plots
          path: plots/tuned/
      - name: Commit artifacts
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add artifacts/tuned/ || true
          git add plots/tuned/ || true
          git commit -m "Add MLflow artifacts via GitHub Actions" || echo "No changes to commit"
          git pull --rebase origin main
          git push https://x:${{ secrets.GITHUB_TOKEN }}@github.com/johanadis/Eksperimen_SML_JohanadiSantoso.git